// entities/route/model/mock.ts
import type { RouteListItem } from '@/shared/api/user/types';

const RouteImage = 'https://picsum.photos/900/600'

export const mockRoutesData: RouteListItem[] = [
    {
        route_id: 'r-001',
        description: 'Прогулка по сонной Москве',
        total_duration: 120,
        total_cost: 1000,
        status: 'going',
        created_at: '2026-04-20T08:00:00Z',
        updated_at: null,
        city: 'Москва',
        image: RouteImage,
        tag: 'romantic',
        interest: 'embankments',
        best_visit_time: 'morning',
    },
    {
        route_id: 'r-002',
        description: 'Архитектурный вояж',
        total_duration: 180,
        total_cost: 500,
        status: 'done',
        created_at: '2026-04-18T10:00:00Z',
        updated_at: '2026-04-18T13:00:00Z',
        city: 'Москва',
        image: RouteImage,
        tag: null,
        interest: 'monuments',
        best_visit_time: 'afternoon',
    },
    {
        route_id: 'r-003',
        description: 'Кофейный тур',
        total_duration: 90,
        total_cost: 0,
        status: 'going',
        created_at: '2026-04-22T09:00:00Z',
        updated_at: null,
        city: 'Санкт-Петербург',
        image: RouteImage,
        tag: null,
        interest: 'coffee',
        best_visit_time: 'morning',
    },
    {
        route_id: 'r-004',
        description: 'Вечерний променад',
        total_duration: 150,
        total_cost: 2000,
        status: 'done',
        created_at: '2026-04-15T18:00:00Z',
        updated_at: '2026-04-15T20:30:00Z',
        city: 'Москва',
        image: RouteImage,
        tag: 'evening',
        interest: 'embankments',
        best_visit_time: 'evening',
    },
    {
        route_id: 'r-005',
        description: 'Парки и скверы',
        total_duration: 100,
        total_cost: 300,
        status: 'cancelled',
        created_at: '2026-04-10T07:00:00Z',
        updated_at: null,
        city: 'Москва',
        image: RouteImage,
        tag: null,
        interest: 'parks',
        best_visit_time: 'morning',
    },
];